os: linux
dist: bionic
notifications:
  slack:
    secure: QdUj1MgtJjL3VK5bjO9U7aijYpedQrrYNYKKoGWzFSBDoB4rGku1TjMo/A6ya0LtGkO89jQtot+b3S/9RSz4QTQqMQMw3PChwPQDjie3Xypww2o2QGuVz+jgg/dOla7NUlfNuxnf+JxZ52y1IzPEev0MYjc+w9PMw7XOTfse3eCozMdejf11UG7o41HAeq4y33TfqBM0jHEn86PMrJz9dPFqMoSG+EFiga+19fw82zqon54RPsTxHT74mSRwi24S0Tt+eANjJuGeDz7Nn2tbPjBx61x+117asxDmvkqLkfzlBrEadd5Q/ks9fIFNU3XjmCrYWU5T0+AXr5WazKycy/5ODYmHX7oIwsLvFHclRLJTVGxZdsdQWu6WwUFeqrNPnuBgaAXFwLVx45jeer3FYjtLtzTGvQjo81UeL9OOeh8iJwc54Uds9m1vHrhkaluI0oBkf0yxCazDKSan6S3l+PHL4IzowJA/VLVYgFnMyIx+277dqfvfYlSWIrc/l1Ig7ZQOSXMBVeg4kKIApJLV62x6Np87/wNlONbsyO0GGrEllIhLaKmW1BiARshNkQhBg1FgxOf6S0YTvIkt16pKVoUA52flRNGLPrcc0lw92KEOd5+Oi+b1ClagVJNb0kLSM/BEeZP2M+nKcBdMlo806VaBuAubX1hOpCPIuRfjR1A=
language: go
go:
  - 1.16.x
env:
  - GOPRIVATE=github.com/KompiTech/*
before_install:
  - git config --global url."git@github.com:KompiTech/".insteadOf "https://github.com/KompiTech/"
script:
  - make test-all
